# Generated by Django 5.1.5 on 2025-08-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_project_owner_project_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('not tested', 'Non testé'), ('correct', 'Correct'), ('incorrect', 'Incorrect')], default='not tested', max_length=20),
        ),
    ]
