# Generated by Django 5.1.5 on 2026-02-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_step_completed_step_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('permalink_url', models.URLField(blank=True)),
                ('workspace_name', models.CharField(blank=True, max_length=255)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('privacy_setting', models.CharField(blank=True, max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-synced_at', 'name'],
            },
        ),
    ]
